# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JJ_LANDING_PAGE.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JJ_LANDING(object):
    def setupUi(self, JJ_LANDING):
        JJ_LANDING.setObjectName("JJ_LANDING")
        JJ_LANDING.resize(1280, 849)
        self.centralwidget = QtWidgets.QWidget(JJ_LANDING)
        self.centralwidget.setObjectName("centralwidget")
        self.BG = QtWidgets.QLabel(self.centralwidget)
        self.BG.setGeometry(QtCore.QRect(0, 0, 1281, 831))
        self.BG.setText("")
        self.BG.setPixmap(QtGui.QPixmap(":/images/BACKGROUND.png"))
        self.BG.setScaledContents(True)
        self.BG.setObjectName("BG")
        self.LOGO = QtWidgets.QLabel(self.centralwidget)
        self.LOGO.setGeometry(QtCore.QRect(500, 100, 341, 231))
        self.LOGO.setText("")
        self.LOGO.setPixmap(QtGui.QPixmap(":/images/JJLOGO.png"))
        self.LOGO.setScaledContents(True)
        self.LOGO.setObjectName("LOGO")
        self.JJ = QtWidgets.QLabel(self.centralwidget)
        self.JJ.setGeometry(QtCore.QRect(280, 360, 921, 81))
        font = QtGui.QFont()
        font.setFamily("Rubik Mono One")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.JJ.setFont(font)
        self.JJ.setStyleSheet("color: #ebe0cc;\n"
"font-size: 100px;\n"
"font-family: \"Rubik Mono One\", sans-serif;\n"
"background: transparent;")
        self.JJ.setScaledContents(True)
        self.JJ.setObjectName("JJ")
        self.ELEVATE = QtWidgets.QLabel(self.centralwidget)
        self.ELEVATE.setGeometry(QtCore.QRect(580, 350, 421, 81))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.ELEVATE.setFont(font)
        self.ELEVATE.setStyleSheet("color: #d75413;\n"
"font-size: 100px;\n"
"font-family: \"Arial Black\", Arial, sans-serif; \n"
"background: transparent;")
        self.ELEVATE.setScaledContents(True)
        self.ELEVATE.setObjectName("ELEVATE")
        self.elv_ur_space = QtWidgets.QLabel(self.centralwidget)
        self.elv_ur_space.setGeometry(QtCore.QRect(280, 440, 711, 71))
        font = QtGui.QFont()
        font.setFamily("Sora Semibold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.elv_ur_space.setFont(font)
        self.elv_ur_space.setStyleSheet("color: #f6f3ee;\n"
"font-size: 35px;\n"
"font-family: \"Sora Semibold\", sans-serif; \n"
"background: transparent;")
        self.elv_ur_space.setScaledContents(True)
        self.elv_ur_space.setObjectName("elv_ur_space")
        self.Supply_Inst_Rep = QtWidgets.QLabel(self.centralwidget)
        self.Supply_Inst_Rep.setGeometry(QtCore.QRect(390, 550, 471, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins Extrabold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.Supply_Inst_Rep.setFont(font)
        self.Supply_Inst_Rep.setStyleSheet("color: #ebe0cc;\n"
"font-size: 20px;\n"
"font-family: \"Poppins Extrabold\", sans-serif;\n"
"background: transparent;")
        self.Supply_Inst_Rep.setScaledContents(True)
        self.Supply_Inst_Rep.setObjectName("Supply_Inst_Rep")
        self.pushButton_contOwner = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_contOwner.setGeometry(QtCore.QRect(70, 650, 221, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(-1)
        self.pushButton_contOwner.setFont(font)
        self.pushButton_contOwner.setStyleSheet("background-color: #f6f3ee;\n"
"border-radius: 15px; \n"
"padding: 4px;\n"
"border: none;\n"
"color: #374550;\n"
"font-size: 18px;\n"
"font-family: \"MS Shell Dlg 2\", sans-serif;")
        self.pushButton_contOwner.setObjectName("pushButton_contOwner")
        self.pushButton_contCashier = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_contCashier.setGeometry(QtCore.QRect(70, 700, 221, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(-1)
        self.pushButton_contCashier.setFont(font)
        self.pushButton_contCashier.setStyleSheet("background-color: #f6f3ee;\n"
"border-radius: 15px; \n"
"padding: 4px;\n"
"border: none;\n"
"color: #374550;\n"
"font-size: 18px;\n"
"font-family: \"MS Shell Dlg 2\", sans-serif;")
        self.pushButton_contCashier.setObjectName("pushButton_contCashier")
        JJ_LANDING.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(JJ_LANDING)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        JJ_LANDING.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(JJ_LANDING)
        self.statusbar.setObjectName("statusbar")
        JJ_LANDING.setStatusBar(self.statusbar)

        self.retranslateUi(JJ_LANDING)
        QtCore.QMetaObject.connectSlotsByName(JJ_LANDING)

    def retranslateUi(self, JJ_LANDING):
        _translate = QtCore.QCoreApplication.translate
        JJ_LANDING.setWindowTitle(_translate("JJ_LANDING", "MainWindow"))
        self.JJ.setText(_translate("JJ_LANDING", "J&J\n"
""))
        self.ELEVATE.setText(_translate("JJ_LANDING", "Elevate\n"
""))
        self.elv_ur_space.setText(_translate("JJ_LANDING", "Elevate Your Space, One Roof at a Time"))
        self.Supply_Inst_Rep.setText(_translate("JJ_LANDING", "Supply                               Install                               Repair    "))
        self.pushButton_contOwner.setText(_translate("JJ_LANDING", "Continue as Owner"))
        self.pushButton_contCashier.setText(_translate("JJ_LANDING", "Continue as Cashier"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JJ_LANDING = QtWidgets.QMainWindow()
    ui = Ui_JJ_LANDING()
    ui.setupUi(JJ_LANDING)
    JJ_LANDING.show()
    sys.exit(app.exec_())
