# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OWNER_SIGNUP.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OwnrSIGNUP(object):
    def setupUi(self, OwnrSIGNUP):
        OwnrSIGNUP.setObjectName("OwnrSIGNUP")
        OwnrSIGNUP.resize(1280, 849)
        self.centralwidget = QtWidgets.QWidget(OwnrSIGNUP)
        self.centralwidget.setStyleSheet("background-color: white;")
        self.centralwidget.setObjectName("centralwidget")
        self.PIC = QtWidgets.QLabel(self.centralwidget)
        self.PIC.setGeometry(QtCore.QRect(0, 0, 1291, 791))
        self.PIC.setMinimumSize(QtCore.QSize(100, 40))
        self.PIC.setText("")
        self.PIC.setPixmap(QtGui.QPixmap(":/images/PIC_log_sign_in.png"))
        self.PIC.setScaledContents(True)
        self.PIC.setObjectName("PIC")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 120, 411, 251))
        self.label.setStyleSheet("background-color: transparent;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/JJLOGO.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(760, 20, 431, 91))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #022162;\n"
"font-size: 40px;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;")
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(730, 110, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #022162;\n"
"font-size: 20px;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;")
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(730, 210, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #022162;\n"
"font-size: 20px;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;")
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(870, 670, 231, 21))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: #022162;")
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.owner_enterfullname = QtWidgets.QLineEdit(self.centralwidget)
        self.owner_enterfullname.setGeometry(QtCore.QRect(710, 160, 521, 51))
        self.owner_enterfullname.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        self.owner_enterfullname.setFont(font)
        self.owner_enterfullname.setStyleSheet("border: 2px solid #022162; \n"
"border-radius: 25px; \n"
"padding: 5px;\n"
"font-size: 18px;\n"
"font-family: \"Verdana\", sans-serif; ")
        self.owner_enterfullname.setObjectName("owner_enterfullname")
        self.owner_enterusername = QtWidgets.QLineEdit(self.centralwidget)
        self.owner_enterusername.setGeometry(QtCore.QRect(710, 270, 521, 51))
        self.owner_enterusername.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        self.owner_enterusername.setFont(font)
        self.owner_enterusername.setStyleSheet("border: 2px solid #022162; \n"
"border-radius: 25px; \n"
"padding: 5px;\n"
"font-size: 18px;\n"
"font-family: \"Verdana\", sans-serif; ")
        self.owner_enterusername.setObjectName("owner_enterusername")
        self.pushButton_signup = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_signup.setGeometry(QtCore.QRect(710, 610, 531, 51))
        self.pushButton_signup.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.pushButton_signup.setFont(font)
        self.pushButton_signup.setStyleSheet("border: 2px solid #374550; \n"
"border-radius: 25px; \n"
"padding: 5px; \n"
"font-size: 22px;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background-color: #374550; \n"
"color: white;")
        self.pushButton_signup.setObjectName("pushButton_signup")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 390, 531, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #ffffff;\n"
"font-size: 27px;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;\n"
"")
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(160, 440, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: #ffffff;\n"
"font-size: 23px;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;\n"
"")
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(80, 540, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: #fff2bd; \n"
"font-size: 20px; \n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent; \n"
"")
        self.label_8.setObjectName("label_8")
        self.pushButton_backtologin = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_backtologin.setGeometry(QtCore.QRect(920, 700, 101, 41))
        self.pushButton_backtologin.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.pushButton_backtologin.setFont(font)
        self.pushButton_backtologin.setStyleSheet("border-radius: 25px; \n"
"padding: 5px; \n"
"font-size: 15px;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background-color: transparent; \n"
"color: #022162;")
        self.pushButton_backtologin.setObjectName("pushButton_backtologin")
        self.owner_enterpassword = QtWidgets.QLineEdit(self.centralwidget)
        self.owner_enterpassword.setGeometry(QtCore.QRect(710, 380, 521, 51))
        self.owner_enterpassword.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        self.owner_enterpassword.setFont(font)
        self.owner_enterpassword.setStyleSheet("border: 2px solid #022162; \n"
"border-radius: 25px; \n"
"padding: 5px;\n"
"font-size: 18px;\n"
"font-family: \"Verdana\", sans-serif; ")
        self.owner_enterpassword.setObjectName("owner_enterpassword")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(730, 320, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: #022162;\n"
"font-size: 20px;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;")
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.owner_confirmpass = QtWidgets.QLineEdit(self.centralwidget)
        self.owner_confirmpass.setGeometry(QtCore.QRect(710, 490, 521, 51))
        self.owner_confirmpass.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        self.owner_confirmpass.setFont(font)
        self.owner_confirmpass.setStyleSheet("border: 2px solid #022162; \n"
"border-radius: 25px; \n"
"padding: 5px;\n"
"font-size: 18px;\n"
"font-family: \"Verdana\", sans-serif; ")
        self.owner_confirmpass.setObjectName("owner_confirmpass")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(730, 430, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: #022162;\n"
"font-size: 20px;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;")
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        OwnrSIGNUP.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OwnrSIGNUP)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        OwnrSIGNUP.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OwnrSIGNUP)
        self.statusbar.setObjectName("statusbar")
        OwnrSIGNUP.setStatusBar(self.statusbar)

        self.retranslateUi(OwnrSIGNUP)
        QtCore.QMetaObject.connectSlotsByName(OwnrSIGNUP)

    def retranslateUi(self, OwnrSIGNUP):
        _translate = QtCore.QCoreApplication.translate
        OwnrSIGNUP.setWindowTitle(_translate("OwnrSIGNUP", "MainWindow"))
        self.label_2.setText(_translate("OwnrSIGNUP", "Create an Account"))
        self.label_3.setText(_translate("OwnrSIGNUP", "Full Name"))
        self.label_4.setText(_translate("OwnrSIGNUP", "Username"))
        self.label_6.setText(_translate("OwnrSIGNUP", "Already have an account?"))
        self.owner_enterfullname.setPlaceholderText(_translate("OwnrSIGNUP", "Enter your full name"))
        self.owner_enterusername.setPlaceholderText(_translate("OwnrSIGNUP", "Enter your username"))
        self.pushButton_signup.setText(_translate("OwnrSIGNUP", "Sign up"))
        self.label_5.setText(_translate("OwnrSIGNUP", "J & J Roofsteel and Gutter Supply"))
        self.label_7.setText(_translate("OwnrSIGNUP", "Moalboal Branch"))
        self.label_8.setText(_translate("OwnrSIGNUP", "Supply       |         Install       |         Repair    "))
        self.pushButton_backtologin.setText(_translate("OwnrSIGNUP", "Login"))
        self.owner_enterpassword.setPlaceholderText(_translate("OwnrSIGNUP", "Enter your password"))
        self.label_9.setText(_translate("OwnrSIGNUP", "Password"))
        self.owner_confirmpass.setPlaceholderText(_translate("OwnrSIGNUP", "Confirm your password"))
        self.label_10.setText(_translate("OwnrSIGNUP", "Confirm Password"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OwnrSIGNUP = QtWidgets.QMainWindow()
    ui = Ui_OwnrSIGNUP()
    ui.setupUi(OwnrSIGNUP)
    OwnrSIGNUP.show()
    sys.exit(app.exec_())
