# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OWNER_LOGIN.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OwnrLOGIN(object):
    def setupUi(self, OwnrLOGIN):
        OwnrLOGIN.setObjectName("OwnrLOGIN")
        OwnrLOGIN.resize(1280, 849)
        self.centralwidget = QtWidgets.QWidget(OwnrLOGIN)
        self.centralwidget.setStyleSheet("background-color: white;")
        self.centralwidget.setObjectName("centralwidget")
        self.PIC = QtWidgets.QLabel(self.centralwidget)
        self.PIC.setGeometry(QtCore.QRect(0, 0, 1291, 791))
        self.PIC.setMinimumSize(QtCore.QSize(100, 40))
        self.PIC.setText("")
        self.PIC.setPixmap(QtGui.QPixmap(":/images/PIC_log_sign_in.png"))
        self.PIC.setScaledContents(True)
        self.PIC.setObjectName("PIC")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 120, 411, 251))
        self.label.setStyleSheet("background-color: transparent;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/JJLOGO.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(880, 70, 181, 91))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #022162;\n"
"font-size: 58px;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;")
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(730, 200, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #022162;\n"
"font-size: 24px;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;")
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(730, 340, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #022162;\n"
"font-size: 24px;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;")
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(860, 610, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: #022162;")
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.ownr_login_usrname = QtWidgets.QLineEdit(self.centralwidget)
        self.ownr_login_usrname.setGeometry(QtCore.QRect(710, 250, 521, 51))
        self.ownr_login_usrname.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        self.ownr_login_usrname.setFont(font)
        self.ownr_login_usrname.setStyleSheet("border: 2px solid #022162; \n"
"border-radius: 25px; \n"
"padding: 5px;\n"
"font-size: 18px;\n"
"font-family: \"Verdana\", sans-serif; ")
        self.ownr_login_usrname.setObjectName("ownr_login_usrname")
        self.ownr_login_password = QtWidgets.QLineEdit(self.centralwidget)
        self.ownr_login_password.setGeometry(QtCore.QRect(710, 400, 521, 51))
        self.ownr_login_password.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        self.ownr_login_password.setFont(font)
        self.ownr_login_password.setStyleSheet("border: 2px solid #022162; \n"
"border-radius: 25px; \n"
"padding: 5px;\n"
"font-size: 18px;\n"
"font-family: \"Verdana\", sans-serif; ")
        self.ownr_login_password.setObjectName("ownr_login_password")
        self.checkBox_rememberme = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_rememberme.setGeometry(QtCore.QRect(730, 470, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        self.checkBox_rememberme.setFont(font)
        self.checkBox_rememberme.setStyleSheet("color: #022162;\n"
"font-size: 17px;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;")
        self.checkBox_rememberme.setObjectName("checkBox_rememberme")
        self.pushButton_LOGIN = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_LOGIN.setGeometry(QtCore.QRect(700, 550, 531, 51))
        self.pushButton_LOGIN.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.pushButton_LOGIN.setFont(font)
        self.pushButton_LOGIN.setStyleSheet("border: 2px solid #374550; \n"
"border-radius: 25px; \n"
"padding: 5px; \n"
"font-size: 22px;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background-color: #374550; \n"
"color: white;")
        self.pushButton_LOGIN.setObjectName("pushButton_LOGIN")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 390, 531, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #ffffff;\n"
"font-size: 27px;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;\n"
"")
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(160, 440, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: #ffffff;\n"
"font-size: 23px;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;\n"
"")
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(80, 540, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: #fff2bd; \n"
"font-size: 20px; \n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent; \n"
"")
        self.label_8.setObjectName("label_8")
        self.pushButton_signup = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_signup.setGeometry(QtCore.QRect(910, 650, 101, 41))
        self.pushButton_signup.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.pushButton_signup.setFont(font)
        self.pushButton_signup.setStyleSheet("border-radius: 25px; \n"
"padding: 5px; \n"
"font-size: 15px;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background-color: transparent; \n"
"color: #022162;")
        self.pushButton_signup.setObjectName("pushButton_signup")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1129, 20, 51, 31))
        self.pushButton_3.setMinimumSize(QtCore.QSize(40, 10))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("border-radius: 13px; \n"
"padding: 1px; \n"
"font-size: 22px;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background-color: #374550; \n"
"color: white;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(1189, 20, 51, 31))
        self.pushButton_4.setMinimumSize(QtCore.QSize(40, 10))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(87)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("border-radius: 13px; \n"
"padding: 1px; \n"
"font-size: 15px;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background-color: #374550; \n"
"color: white;")
        self.pushButton_4.setObjectName("pushButton_4")
        OwnrLOGIN.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OwnrLOGIN)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        OwnrLOGIN.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OwnrLOGIN)
        self.statusbar.setObjectName("statusbar")
        OwnrLOGIN.setStatusBar(self.statusbar)

        self.retranslateUi(OwnrLOGIN)
        QtCore.QMetaObject.connectSlotsByName(OwnrLOGIN)

    def retranslateUi(self, OwnrLOGIN):
        _translate = QtCore.QCoreApplication.translate
        OwnrLOGIN.setWindowTitle(_translate("OwnrLOGIN", "MainWindow"))
        self.label_2.setText(_translate("OwnrLOGIN", "Login"))
        self.label_3.setText(_translate("OwnrLOGIN", "Username"))
        self.label_4.setText(_translate("OwnrLOGIN", "Password"))
        self.label_6.setText(_translate("OwnrLOGIN", "Don\'t have an account?"))
        self.ownr_login_usrname.setPlaceholderText(_translate("OwnrLOGIN", "Enter your username"))
        self.ownr_login_password.setPlaceholderText(_translate("OwnrLOGIN", "Enter your password"))
        self.checkBox_rememberme.setText(_translate("OwnrLOGIN", "Remember me"))
        self.pushButton_LOGIN.setText(_translate("OwnrLOGIN", "Login"))
        self.label_5.setText(_translate("OwnrLOGIN", "J & J Roofsteel and Gutter Supply"))
        self.label_7.setText(_translate("OwnrLOGIN", "Moalboal Branch"))
        self.label_8.setText(_translate("OwnrLOGIN", "Supply       |         Install       |         Repair    "))
        self.pushButton_signup.setText(_translate("OwnrLOGIN", "Sign Up"))
        self.pushButton_3.setText(_translate("OwnrLOGIN", "-"))
        self.pushButton_4.setText(_translate("OwnrLOGIN", "x"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OwnrLOGIN = QtWidgets.QMainWindow()
    ui = Ui_OwnrLOGIN()
    ui.setupUi(OwnrLOGIN)
    OwnrLOGIN.show()
    sys.exit(app.exec_())
