# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OWNER_DASHBOARD.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OWNER_DASHBOARD(object):
    def setupUi(self, OWNER_DASHBOARD):
        OWNER_DASHBOARD.setObjectName("OWNER_DASHBOARD")
        OWNER_DASHBOARD.resize(1280, 849)
        self.centralwidget = QtWidgets.QWidget(OWNER_DASHBOARD)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-1430, -150, 2721, 1361))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/PIC_log_sign_in.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 1231, 511))
        self.label_2.setStyleSheet("color: #022162;\n"
"font-size: 58px;\n"
"font-weight: 700;\n"
"font-family: \"Verdana\", sans-serif; \n"
"background: transparent;")
        self.label_2.setObjectName("label_2")
        self.pushButton_OwnrDASH = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_OwnrDASH.setGeometry(QtCore.QRect(30, 100, 201, 71))
        self.pushButton_OwnrDASH.setObjectName("pushButton_OwnrDASH")
        OWNER_DASHBOARD.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OWNER_DASHBOARD)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        OWNER_DASHBOARD.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OWNER_DASHBOARD)
        self.statusbar.setObjectName("statusbar")
        OWNER_DASHBOARD.setStatusBar(self.statusbar)

        self.retranslateUi(OWNER_DASHBOARD)
        QtCore.QMetaObject.connectSlotsByName(OWNER_DASHBOARD)

    def retranslateUi(self, OWNER_DASHBOARD):
        _translate = QtCore.QCoreApplication.translate
        OWNER_DASHBOARD.setWindowTitle(_translate("OWNER_DASHBOARD", "MainWindow"))
        self.label_2.setText(_translate("OWNER_DASHBOARD", "OWNER DASHBOARD WALA PA HUHU"))
        self.pushButton_OwnrDASH.setText(_translate("OWNER_DASHBOARD", "DASHBOARD"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OWNER_DASHBOARD = QtWidgets.QMainWindow()
    ui = Ui_OWNER_DASHBOARD()
    ui.setupUi(OWNER_DASHBOARD)
    OWNER_DASHBOARD.show()
    sys.exit(app.exec_())
